name: Reusable Golang setup workflow
description: Setup git over HTTPS to enable golang to download private dependencies

inputs:
  gh_access_token:
    required: true
  go_version:
    required: false
    default: 1.22.0

runs:
  using: "composite"
  steps:
    - name: Setup git over HTTPS
      uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: ${{inputs.gh_access_token}}

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{inputs.go_version}}

    - name: Fetch dependencies
      run: |
        go mod vendor
      shell: bash

    - name: Post Composite Action
      run: |
        echo "finished composite action"
      shell: bash
